// generated by https://www.json-generator.com/
module.exports = [
  {
    '_id': '5a97ba8e62ba60b9df44356a',
    'index': 0,
    'guid': '81a2f050-0f0b-4c83-b04a-020cb839c84a',
    'isActive': false,
    'balance': '$1,384.07',
    'picture': 'http://placehold.it/32x32',
    'age': 37,
    'eyeColor': 'blue',
    'name': 'Yvette Casey',
    'gender': 'female',
    'company': 'LOTRON',
    'email': 'yvettecasey@lotron.com',
    'phone': '+1 (961) 435-2825',
    'address': '592 Hinsdale Street, Chautauqua, Kentucky, 9394',
    'about': 'Exercitation sit duis ex officia officia. Reprehenderit nulla non velit aliqua voluptate nostrud enim officia ut amet nulla duis mollit do. Voluptate Lorem dolore fugiat mollit.\r\n',
    'registered': '2017-09-28T04:01:40 -02:00',
    'latitude': 69.080994,
    'longitude': -168.708373,
    'tags': [
      'commodo',
      'ad',
      'ea',
      'labore',
      'laborum',
      'esse',
      'deserunt'
    ],
    'friends': [
      {
        'id': 0,
        'name': 'Salas Hudson'
      },
      {
        'id': 1,
        'name': 'Kristina Schmidt'
      },
      {
        'id': 2,
        'name': 'Avery Calderon'
      }
    ],
    'greeting': 'Hello, Yvette Casey! You have 4 unread messages.',
    'favoriteFruit': 'banana'
  },
  {
    '_id': '5a97ba8e58093981dc4cad01',
    'index': 1,
    'guid': '7658db69-aaea-4f8f-94b1-9a19363825cd',
    'isActive': true,
    'balance': '$2,899.23',
    'picture': 'http://placehold.it/32x32',
    'age': 23,
    'eyeColor': 'green',
    'name': 'Malinda Kaufman',
    'gender': 'female',
    'company': 'STREZZO',
    'email': 'malindakaufman@strezzo.com',
    'phone': '+1 (817) 453-2019',
    'address': '788 Division Avenue, Bergoo, Indiana, 437',
    'about': 'Excepteur culpa ut id fugiat deserunt amet eu. Consectetur ea officia anim ea laborum ea veniam amet anim magna consequat nostrud laborum. Dolore ad deserunt pariatur reprehenderit esse aute. Sint ut id commodo aute. Cillum consequat sit incididunt duis non dolor aliquip ut. Officia culpa sint aliquip adipisicing minim.\r\n',
    'registered': '2015-08-26T08:21:38 -02:00',
    'latitude': 52.903954,
    'longitude': -174.978999,
    'tags': [
      'aliqua',
      'nulla',
      'magna',
      'elit',
      'excepteur',
      'deserunt',
      'in'
    ],
    'friends': [
      {
        'id': 0,
        'name': 'Casey Leon'
      },
      {
        'id': 1,
        'name': 'Tina Buchanan'
      },
      {
        'id': 2,
        'name': 'Pamela Justice'
      }
    ],
    'greeting': 'Hello, Malinda Kaufman! You have 3 unread messages.',
    'favoriteFruit': 'strawberry'
  },
  {
    '_id': '5a97ba8ea944c3c63f1c16c3',
    'index': 2,
    'guid': 'b517ee56-c024-4cce-83ec-19a414b84e33',
    'isActive': false,
    'balance': '$1,478.57',
    'picture': 'http://placehold.it/32x32',
    'age': 36,
    'eyeColor': 'blue',
    'name': 'Ursula Malone',
    'gender': 'female',
    'company': 'BUGSALL',
    'email': 'ursulamalone@bugsall.com',
    'phone': '+1 (905) 410-3652',
    'address': '309 Stoddard Place, Lumberton, Rhode Island, 300',
    'about': 'Magna eu dolore sunt quis laborum. Veniam laborum consequat ipsum adipisicing eiusmod eiusmod ut. Proident irure et reprehenderit ea elit mollit. Deserunt pariatur nulla pariatur excepteur ipsum aliqua dolore cillum nulla adipisicing eu veniam.\r\n',
    'registered': '2016-07-05T08:47:17 -02:00',
    'latitude': -59.404512,
    'longitude': -135.977976,
    'tags': [
      'non',
      'cupidatat',
      'minim',
      'non',
      'incididunt',
      'tempor',
      'officia'
    ],
    'friends': [
      {
        'id': 0,
        'name': 'Patty Smith'
      },
      {
        'id': 1,
        'name': 'Alexander Torres'
      },
      {
        'id': 2,
        'name': 'Lopez Valdez'
      }
    ],
    'greeting': 'Hello, Ursula Malone! You have 1 unread messages.',
    'favoriteFruit': 'banana'
  },
  {
    '_id': '5a97ba8eb3d03c031463833d',
    'index': 3,
    'guid': 'cbc1571d-db2d-49a0-b477-84d5c54498a9',
    'isActive': false,
    'balance': '$2,373.13',
    'picture': 'http://placehold.it/32x32',
    'age': 23,
    'eyeColor': 'brown',
    'name': 'Melva Madden',
    'gender': 'female',
    'company': 'COLLAIRE',
    'email': 'melvamadden@collaire.com',
    'phone': '+1 (814) 496-2068',
    'address': '702 Underhill Avenue, Soudan, Texas, 730',
    'about': 'Excepteur ipsum aliquip ad sint exercitation aliquip labore reprehenderit minim. Magna cillum incididunt exercitation tempor quis. Adipisicing velit veniam officia labore ex duis consequat duis quis adipisicing consectetur nulla duis pariatur. Dolor ex consectetur cillum sint ipsum mollit Lorem labore non laborum ex duis nulla eiusmod.\r\n',
    'registered': '2017-04-25T10:59:42 -02:00',
    'latitude': 54.892273,
    'longitude': 69.598987,
    'tags': [
      'nulla',
      'magna',
      'incididunt',
      'nisi',
      'consequat',
      'consectetur',
      'adipisicing'
    ],
    'friends': [
      {
        'id': 0,
        'name': 'Keri Curtis'
      },
      {
        'id': 1,
        'name': 'Jeanie Reynolds'
      },
      {
        'id': 2,
        'name': 'Gilmore Haney'
      }
    ],
    'greeting': 'Hello, Melva Madden! You have 1 unread messages.',
    'favoriteFruit': 'banana'
  },
  {
    '_id': '5a97ba8ef3c5f1a658073add',
    'index': 4,
    'guid': '7c4ec526-3997-4209-9db0-7a4a776384a8',
    'isActive': true,
    'balance': '$1,922.87',
    'picture': 'http://placehold.it/32x32',
    'age': 20,
    'eyeColor': 'green',
    'name': 'Garrett Rogers',
    'gender': 'male',
    'company': 'PHEAST',
    'email': 'garrettrogers@pheast.com',
    'phone': '+1 (945) 519-2936',
    'address': '762 Jay Street, Lowgap, Washington, 2911',
    'about': 'Sit officia dolor velit ullamco ipsum proident ipsum labore quis proident do labore laborum. Duis sunt sint ad cillum esse anim. Sunt est officia consectetur labore laborum.\r\n',
    'registered': '2017-12-25T05:55:55 -01:00',
    'latitude': -67.894581,
    'longitude': -0.106974,
    'tags': [
      'irure',
      'aute',
      'in',
      'sunt',
      'irure',
      'cupidatat',
      'esse'
    ],
    'friends': [
      {
        'id': 0,
        'name': 'Blair Mills'
      },
      {
        'id': 1,
        'name': 'Heidi Winters'
      },
      {
        'id': 2,
        'name': 'Edna Moran'
      }
    ],
    'greeting': 'Hello, Garrett Rogers! You have 7 unread messages.',
    'favoriteFruit': 'apple'
  },
  {
    '_id': '5a97ba8e9888e1484556b4f1',
    'index': 5,
    'guid': 'c63b56db-644f-496f-9d1d-5aa448649ba8',
    'isActive': true,
    'balance': '$2,873.51',
    'picture': 'http://placehold.it/32x32',
    'age': 36,
    'eyeColor': 'blue',
    'name': 'Valencia Rivera',
    'gender': 'male',
    'company': 'GAZAK',
    'email': 'valenciarivera@gazak.com',
    'phone': '+1 (850) 491-3282',
    'address': '463 Sunnyside Avenue, Alfarata, Virgin Islands, 1870',
    'about': 'Cillum dolor commodo aliqua ex elit adipisicing non cillum laborum qui commodo aliqua enim. Qui sit velit nostrud eiusmod ea non irure eu nostrud nostrud ex et adipisicing. Adipisicing commodo do sunt id officia ad est adipisicing do nulla dolore ea commodo. Irure sint excepteur mollit non est quis. Anim voluptate ipsum consectetur laboris nostrud sint elit incididunt magna ullamco culpa. Fugiat consequat voluptate id laboris proident nisi aliquip nostrud tempor ex veniam.\r\n',
    'registered': '2015-10-15T05:39:04 -02:00',
    'latitude': 73.291847,
    'longitude': 155.51828,
    'tags': [
      'exercitation',
      'aute',
      'eu',
      'in',
      'sit',
      'non',
      'consectetur'
    ],
    'friends': [
      {
        'id': 0,
        'name': 'Dominique Freeman'
      },
      {
        'id': 1,
        'name': 'David Walls'
      },
      {
        'id': 2,
        'name': 'Duran Graham'
      }
    ],
    'greeting': 'Hello, Valencia Rivera! You have 5 unread messages.',
    'favoriteFruit': 'strawberry'
  },
  {
    '_id': '5a97ba8ec6b0f46ef2b5b6d3',
    'index': 6,
    'guid': 'ed226a8e-ff13-41fe-acf0-9b1ac0d6192f',
    'isActive': false,
    'balance': '$1,901.72',
    'picture': 'http://placehold.it/32x32',
    'age': 26,
    'eyeColor': 'brown',
    'name': 'Rosa Sharpe',
    'gender': 'male',
    'company': 'ANIXANG',
    'email': 'rosasharpe@anixang.com',
    'phone': '+1 (817) 488-3116',
    'address': '731 Cornelia Street, Maury, Florida, 8539',
    'about': 'Esse Lorem irure dolore deserunt sint aute in eiusmod cillum exercitation. Consequat velit voluptate consectetur culpa dolor enim aute ea deserunt. Voluptate veniam aliquip labore mollit officia nostrud. Ea exercitation labore qui Lorem id ex sint occaecat laborum.\r\n',
    'registered': '2017-04-01T02:11:47 -02:00',
    'latitude': -39.804995,
    'longitude': -126.146291,
    'tags': [
      'labore',
      'ad',
      'duis',
      'labore',
      'laborum',
      'fugiat',
      'officia'
    ],
    'friends': [
      {
        'id': 0,
        'name': 'Michael Day'
      },
      {
        'id': 1,
        'name': 'Sweeney Chang'
      },
      {
        'id': 2,
        'name': 'Hood Hoover'
      }
    ],
    'greeting': 'Hello, Rosa Sharpe! You have 10 unread messages.',
    'favoriteFruit': 'apple'
  }
];